# 2. NumPy User Guide
https://docs.scipy.org/doc/numpy/user/  
https://docs.scipy.org/doc/numpy/reference/index.html   
https://docs.scipy.org/doc/numpy/contents.html  

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## 1. Data types
https://docs.scipy.org/doc/numpy/user/basics.types.html

### Array types and conversions between types

```
NumPy supports a much greater variety of numerical types than Python does. This section shows which are available, and how to modify an array’s data-type.  

Data type	Description
bool_	Boolean (True or False) stored as a byte
int_	Default integer type (same as C long; normally either int64 or int32)
intc	Identical to C int (normally int32 or int64)
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8	Byte (-128 to 127)
int16	Integer (-32768 to 32767)
int32	Integer (-2147483648 to 2147483647)
int64	Integer (-9223372036854775808 to 9223372036854775807)
uint8	Unsigned integer (0 to 255)
uint16	Unsigned integer (0 to 65535)
uint32	Unsigned integer (0 to 4294967295)
uint64	Unsigned integer (0 to 18446744073709551615)
float_	Shorthand for float64.
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_	Shorthand for complex128.
complex64	Complex number, represented by two 32-bit floats (real and imaginary components)
complex128	Complex number, represented by two 64-bit floats (real and imaginary components)
Additionally to intc the platform dependent C integer types short, long, longlong and their unsigned versions are defined.

NumPy numerical types are instances of dtype (data-type) objects, each having unique characteristics. Once you have imported NumPy using

>>>
>>> import numpy as np
the dtypes are available as np.bool_, np.float32, etc.

Advanced types, not listed in the table above, are explored in section Structured arrays.

There are 5 basic numerical types representing booleans (bool), integers (int), unsigned integers (uint) floating point (float) and complex. Those with numbers in their name indicate the bitsize of the type (i.e. how many bits are needed to represent a single value in memory). Some types, such as int and intp, have differing bitsizes, dependent on the platforms (e.g. 32-bit vs. 64-bit machines). This should be taken into account when interfacing with low-level code (such as C or Fortran) where the raw memory is addressed.

Data-types can be used as functions to convert python numbers to array scalars (see the array scalar section for an explanation), python sequences of numbers to arrays of that type, or as arguments to the dtype keyword that many numpy functions or methods accept. Some examples:
```

In [2]:
import numpy as np
x = np.float32(1.0)
x

1.0

In [3]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [4]:
array([1, 2, 4])
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

Array types can also be referred to by character codes, mostly to retain backward compatibility with older packages such as Numeric. Some documentation may still refer to these, for example:

In [5]:
np.array([1, 2, 3], dtype='f')

array([ 1.,  2.,  3.], dtype=float32)

We recommend using dtype objects instead.

To convert the type of an array, use the ***.astype()*** method (preferred) or the type itself as a function. For example:

In [6]:
z.astype(float)

array([ 0.,  1.,  2.])

In [7]:
np.int8(z)

array([0, 1, 2], dtype=int8)

Note that, above, we use the Python float object as a dtype. NumPy knows that int refers to np.int_, bool means np.bool_, that float is np.float_ and complex is np.complex_. The other data-types do not have Python equivalents.

To determine the type of an array, look at the dtype attribute:

In [8]:
z.dtype

dtype('uint8')

dtype objects also contain information about the type, such as its bit-width and its byte-order. The data type can also be used indirectly to query properties of the type, such as whether it is an integer:

In [9]:
d = np.dtype(int)
d

dtype('int64')

In [10]:
np.issubdtype(d, int)

True

In [11]:
np.issubdtype(d, float)

False

### Array Scalars

NumPy generally returns elements of arrays as ***array scalars*** (a scalar with an associated dtype). Array scalars differ from Python scalars, but for the most part they can be used interchangeably (the primary exception is for versions of Python older than v2.x, where integer array scalars cannot act as indices for lists and tuples). There are some exceptions, such as when code requires very specific attributes of a scalar or when it checks specifically whether a value is a Python scalar. Generally, problems are easily fixed by explicitly converting array scalars to Python scalars, using the corresponding Python type function (e.g., int, float, complex, str, unicode).

The primary advantage of using array scalars is that they preserve the array type (Python may not have a matching scalar type available, e.g. int16). Therefore, the use of array scalars ensures identical behaviour between arrays and scalars, irrespective of whether the value is inside an array or not. NumPy scalars also have many of the same methods arrays do.

### Extended Precision

## 2. Array creation
https://docs.scipy.org/doc/numpy/user/basics.creation.html

There are 5 general mechanisms for creating arrays:  

1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)  

This section will not cover means of replicating, joining, or otherwise expanding or mutating existing arrays. Nor will it cover creating object arrays or structured arrays. Both of those are covered in their own sections.

### Converting Python array_like Objects to NumPy Arrays

In [12]:
np.array([2,3,1,0])

array([2, 3, 1, 0])

In [13]:
np.array([2, 3, 1, 0])

array([2, 3, 1, 0])

In [14]:
np.array([[1,2.0],[0,0],(1+1j,3.)]) # note mix of tuple and lists,mand types

array([[ 1.+0.j,  2.+0.j],
       [ 0.+0.j,  0.+0.j],
       [ 1.+1.j,  3.+0.j]])

In [15]:
np.array([[ 1.+0.j, 2.+0.j], [ 0.+0.j, 0.+0.j], [ 1.+1.j, 3.+0.j]])

array([[ 1.+0.j,  2.+0.j],
       [ 0.+0.j,  0.+0.j],
       [ 1.+1.j,  3.+0.j]])

### Intrinsic NumPy Array Creation

In [16]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2, 10, dtype=np.float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [19]:
np.arange(2, 3, 0.1)

array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9])

linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. For example:

In [20]:
np.linspace(1., 4., 6)

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ])

***indices()*** will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension. An example illustrates much better than a verbal description:

In [21]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

### Reading Arrays From Disk

## 3. I/O with NumPy
https://docs.scipy.org/doc/numpy/user/basics.io.html

## 4. Indexing
https://docs.scipy.org/doc/numpy/user/basics.indexing.html

### Single element indexing

In [22]:
x = np.arange(10)
x[2]

2

In [23]:
x[-2]

8

In [24]:
x.shape = (2,5) # now x is 2-dimensional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
x[1,3]

8

In [26]:
x[1,-1]

9

In [27]:
x[0]

array([0, 1, 2, 3, 4])

In [28]:
x[0][2] 

2

### Other indexing options

In [29]:
x = np.arange(10)
x[2:5]

array([2, 3, 4])

In [30]:
x[:-7]

array([0, 1, 2])

In [31]:
x[1:7:2]

array([1, 3, 5])

In [32]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [33]:
y[1:5:2,::3] 

array([[ 7, 10, 13],
       [21, 24, 27]])

### Index arrays

In [34]:
x = np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [35]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [36]:
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [37]:
x[np.array([3, 3, 20, 8])]

IndexError: index 20 is out of bounds for axis 1 with size 9

Generally speaking, what is returned when index arrays are used is an array with the same shape as the index array, but with the type and values of the array being indexed. As an example, we can use a ***multidimensional index array*** instead:

In [38]:
x[np.array([[1,1],[2,3]])]

array([[9, 9],
       [8, 7]])

### Indexing Multi-dimensional arrays

In [39]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [40]:
y[np.array([0,2,4]), np.array([0,1,2])] 

array([ 0, 15, 30])

In [41]:
y[np.array([0,2,4]), np.array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [42]:
y[np.array([0,2,4]), 1]

array([ 1, 15, 29])

In [43]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

### Boolean or “mask” index arrays

In [44]:
b = y>20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]], dtype=bool)

In [45]:
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [46]:
b[:,5] # use a 1-D boolean whose first dim agrees with the first dim of y

array([False, False, False,  True,  True], dtype=bool)

In [47]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In general, when the boolean array has fewer dimensions than the array being indexed, this is equivalent to y[b, ...], which means y is indexed by b followed by as many : as are needed to fill out the rank of y. Thus the shape of the result is one dimension containing the number of True elements of the boolean array, followed by the remaining dimensions of the array being indexed.

For example, using a 2-D boolean array of shape (2,3) with four True elements to select rows from a 3-D array of shape (2,3,5) results in a 2-D result of shape (4,5):

In [48]:
x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [59]:
b = np.array([[True, True, False], [False, True, True]])
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### Combining index arrays with slices

In [60]:
y[np.array([0,2,4]),1:3] 

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [61]:
y[b[:,2],1:3]

/home/wei/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 2
  if __name__ == '__main__':


array([[8, 9]])

### Structural indexing tools

In [62]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [63]:
y.shape 

(5, 7)

In [64]:
y[:,np.newaxis,:].shape

(5, 1, 7)

In [65]:
y[:,np.newaxis,:]

array([[[ 0,  1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27]],

       [[28, 29, 30, 31, 32, 33, 34]]])

In [66]:
x = np.arange(5)
x[:,np.newaxis] + x[np.newaxis,:] 

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [67]:
z = np.arange(81).reshape(3,3,3,3)
z[1,...,2]
# This is equivalent to:

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [68]:
z[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

### Assigning values to indexed arrays

In [69]:
x = np.arange(10)
x[2:7] = 1
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [70]:
x[2:7] = np.arange(5)
x[1] = 1.2
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [71]:
x[1]

1

In [72]:
x[1] = 1.2j

TypeError: can't convert complex to int

Unlike some of the references (such as array and mask indices) assignments are always made to ***the original data in the array*** (indeed, nothing else would make sense!). Note though, that some actions may not work as one may naively expect. This particular example is often surprising to people:

In [74]:
x = np.arange(0, 50, 10)
x

array([ 0, 10, 20, 30, 40])

In [75]:
x[np.array([1, 1, 3, 1])] += 1
x

array([ 0, 11, 20, 31, 40])

### Dealing with variable numbers of indices within programs

In [76]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [77]:
indices = (1,1,1,1)
z[indices] 

40

In [78]:
indices = (1,1,1,slice(0,2)) # same as [1,1,1,0:2]
z[indices]

array([39, 40])

Likewise, ellipsis can be specified by code by using the Ellipsis object:

In [81]:
indices = (1, Ellipsis, 1) # same as [1,...,1]
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [80]:
Ellipsis

Ellipsis

For this reason it is possible to use the output from the np.where() function directly as an index since it always returns a tuple of index arrays.

Because the special treatment of tuples, they are not automatically converted to an array as a list would be. As an example:

In [82]:
z[[1,1,1,1]] # produces a large array

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [84]:
z[(1,1,1,1)] # returns a single value

40

## 5. Broadcasting

## 6. Byte-swapping

## 7. Structured arrays

In [85]:
x = np.array([(1, 2., 'Hello'), (2, 3., "World")], dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])
x

array([(1, 2.0, b'Hello'), (2, 3.0, b'World')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [86]:
x[1]

(2, 3.0, b'World')

In [87]:
y = x['bar']
y

array([ 2.,  3.], dtype=float32)

In [88]:
y[:] = 2*y
y

array([ 4.,  6.], dtype=float32)

In [89]:
x

array([(1, 4.0, b'Hello'), (2, 6.0, b'World')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [90]:
x[1] = (-1,-1.,"Master")
x

array([(1, 4.0, b'Hello'), (-1, -1.0, b'Master')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [91]:
y

array([ 4., -1.], dtype=float32)

### Defining Structured Arrays

In [129]:
x = np.zeros(3, dtype='3int8, float32, (2,3)float64')
x

array([([0, 0, 0], 0.0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]),
       ([0, 0, 0], 0.0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]),
       ([0, 0, 0], 0.0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])], 
      dtype=[('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

In [130]:
x = np.zeros(3, dtype=('i4',[('r','u1'), ('g','u1'), ('b','u1'), ('a','u1')]))
x

array([0, 0, 0], dtype=int32)

In [131]:
x['r']

array([0, 0, 0], dtype=uint8)

In [132]:
x = np.zeros(3, dtype=[('x','f4'),('y',np.float32),('value','f4',(2,2))])
x

array([(0.0, 0.0, [[0.0, 0.0], [0.0, 0.0]]),
       (0.0, 0.0, [[0.0, 0.0], [0.0, 0.0]]),
       (0.0, 0.0, [[0.0, 0.0], [0.0, 0.0]])], 
      dtype=[('x', '<f4'), ('y', '<f4'), ('value', '<f4', (2, 2))])

In [133]:
x = np.zeros(3, dtype={'names':['col1', 'col2'], 'formats':['i4','f4']})
x

array([(0, 0.0), (0, 0.0), (0, 0.0)], 
      dtype=[('col1', '<i4'), ('col2', '<f4')])

In [134]:
x = np.zeros(3, dtype={'col1':('i1',0,'title 1'), 'col2':('f4',1,'title 2')})
x

array([(0, 0.0), (0, 0.0), (0, 0.0)], 
      dtype=[(('title 1', 'col1'), 'i1'), (('title 2', 'col2'), '<f4')])

### Accessing and modifying field names

In [94]:
x

array([(1, 4.0, b'Hello'), (-1, -1.0, b'Master')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [93]:
x.dtype.names

('foo', 'bar', 'baz')

In [95]:
x.dtype.names = ('x', 'y')
x

ValueError: must replace all names at once with a sequence of length 3

In [97]:
x.dtype.names = ('x', 'y', 'z') # wrong number of names
x

array([(1, 4.0, b'Hello'), (-1, -1.0, b'Master')], 
      dtype=[('x', '<i4'), ('y', '<f4'), ('z', 'S10')])

### Accessing field titles

In [103]:
x.dtype.fields['x'] 

(dtype('int32'), 0)

### Accessing multiple fields at once

In [105]:
x = np.array([(1.5,2.5,(1.0,2.0)),(3.,4.,(4.,5.)),(1.,3.,(2.,6.))],
        dtype=[('x','f4'),('y',np.float32),('value','f4',(2,2))])
x
# Notice that x is created with a list of tuples.

array([(1.5, 2.5, [[1.0, 2.0], [1.0, 2.0]]),
       (3.0, 4.0, [[4.0, 5.0], [4.0, 5.0]]),
       (1.0, 3.0, [[2.0, 6.0], [2.0, 6.0]])], 
      dtype=[('x', '<f4'), ('y', '<f4'), ('value', '<f4', (2, 2))])

In [106]:
x[['x','y']]

array([(1.5, 2.5), (3.0, 4.0), (1.0, 3.0)], 
      dtype=[('x', '<f4'), ('y', '<f4')])

In [107]:
x[['x','value']]

array([(1.5, [[1.0, 2.0], [1.0, 2.0]]), (3.0, [[4.0, 5.0], [4.0, 5.0]]),
       (1.0, [[2.0, 6.0], [2.0, 6.0]])], 
      dtype=[('x', '<f4'), ('value', '<f4', (2, 2))])

In [108]:
x[['y','x']]

array([(2.5, 1.5), (4.0, 3.0), (3.0, 1.0)], 
      dtype=[('y', '<f4'), ('x', '<f4')])

### Filling structured arrays

In [109]:
arr = np.zeros((5,), dtype=[('var1','f8'),('var2','f8')])
arr

array([(0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0)], 
      dtype=[('var1', '<f8'), ('var2', '<f8')])

In [111]:
arr['var1'] = np.arange(5)
arr

array([(0.0, 0.0), (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0)], 
      dtype=[('var1', '<f8'), ('var2', '<f8')])

In [112]:
arr[0] = (10,20)
arr

array([(10.0, 20.0), (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0)], 
      dtype=[('var1', '<f8'), ('var2', '<f8')])

### Record Arrays

For convenience, numpy provides “record arrays” which allow one to access fields of structured arrays by attribute rather than by index. Record arrays are structured arrays wrapped using a subclass of ndarray, ***numpy.recarray***, which allows field access by attribute on the array object, and record arrays also use a special datatype, ***numpy.record***, which allows field access by attribute on the individual elements of the array.

The simplest way to create a record array is with ***numpy.rec.array***:

In [114]:
recordarr = np.rec.array([(1,2.,'Hello'),(2,3.,"World")], 
                   dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])
recordarr

rec.array([(1, 2.0, b'Hello'), (2, 3.0, b'World')], 
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [115]:
recordarr.bar

array([ 2.,  3.], dtype=float32)

In [116]:
recordarr[1:2]

rec.array([(2, 3.0, b'World')], 
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [117]:
recordarr[1:2].foo

array([2], dtype=int32)

In [118]:
recordarr.foo[1:2]

array([2], dtype=int32)

In [119]:
recordarr[1].baz

b'World'

In [120]:
arr = array([(1,2.,'Hello'),(2,3.,"World")], 
            dtype=[('foo', 'i4'), ('bar', 'f4'), ('baz', 'S10')])
arr

array([(1, 2.0, b'Hello'), (2, 3.0, b'World')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [121]:
recordarr = np.rec.array(arr)
recordarr

rec.array([(1, 2.0, b'Hello'), (2, 3.0, b'World')], 
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [122]:
arr = np.array([(1,2.,'Hello'),(2,3.,"World")], 
               dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'a10')])
arr

array([(1, 2.0, b'Hello'), (2, 3.0, b'World')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [123]:
recordarr = arr.view(dtype=dtype((np.record, arr.dtype)), 
                     type=np.recarray)
recordarr 

rec.array([(1, 2.0, b'Hello'), (2, 3.0, b'World')], 
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [124]:
recordarr = arr.view(np.recarray)
recordarr.dtype 

dtype((numpy.record, [('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]))

In [125]:
arr2 = recordarr.view(recordarr.dtype.fields or recordarr.dtype, np.ndarray)
arr2

array([(1, 2.0, b'Hello'), (2, 3.0, b'World')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [126]:
recordarr = np.rec.array([('Hello', (1,2)),("World", (3,4))], 
                dtype=[('foo', 'S6'),('bar', [('A', int), ('B', int)])])
recordarr

rec.array([(b'Hello', (1, 2)), (b'World', (3, 4))], 
          dtype=[('foo', 'S6'), ('bar', [('A', '<i8'), ('B', '<i8')])])

In [127]:
type(recordarr.foo)

numpy.ndarray

In [128]:
type(recordarr.bar) 

numpy.recarray